// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: calendar_events.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createCalendarEvent = `-- name: CreateCalendarEvent :one
INSERT INTO
    calendar_events (
        title,
        description,
        start_time,
        end_time,
        all_day,
        location,
        calendar_id
    )
VALUES
    (?, ?, ?, ?, ?, ?, ?) RETURNING id, title, description, start_time, end_time, all_day, location, calendar_id
`

type CreateCalendarEventParams struct {
	Title       string
	Description sql.NullString
	StartTime   time.Time
	EndTime     sql.NullTime
	AllDay      bool
	Location    string
	CalendarID  int64
}

func (q *Queries) CreateCalendarEvent(ctx context.Context, arg CreateCalendarEventParams) (CalendarEvent, error) {
	row := q.db.QueryRowContext(ctx, createCalendarEvent,
		arg.Title,
		arg.Description,
		arg.StartTime,
		arg.EndTime,
		arg.AllDay,
		arg.Location,
		arg.CalendarID,
	)
	var i CalendarEvent
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.StartTime,
		&i.EndTime,
		&i.AllDay,
		&i.Location,
		&i.CalendarID,
	)
	return i, err
}

const deleteCalendarEvent = `-- name: DeleteCalendarEvent :exec
DELETE FROM calendar_events
WHERE
    id = ?
`

func (q *Queries) DeleteCalendarEvent(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteCalendarEvent, id)
	return err
}

const getCalendarEvent = `-- name: GetCalendarEvent :one
SELECT
    id, title, description, start_time, end_time, all_day, location, calendar_id
FROM
    calendar_events
WHERE
    id = ?
LIMIT
    1
`

func (q *Queries) GetCalendarEvent(ctx context.Context, id int64) (CalendarEvent, error) {
	row := q.db.QueryRowContext(ctx, getCalendarEvent, id)
	var i CalendarEvent
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.StartTime,
		&i.EndTime,
		&i.AllDay,
		&i.Location,
		&i.CalendarID,
	)
	return i, err
}

const listCalendarEvents = `-- name: ListCalendarEvents :many
SELECT
    id, title, description, start_time, end_time, all_day, location, calendar_id
FROM
    calendar_events
ORDER BY
    start_time
`

func (q *Queries) ListCalendarEvents(ctx context.Context) ([]CalendarEvent, error) {
	rows, err := q.db.QueryContext(ctx, listCalendarEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CalendarEvent
	for rows.Next() {
		var i CalendarEvent
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.StartTime,
			&i.EndTime,
			&i.AllDay,
			&i.Location,
			&i.CalendarID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCalendarEvent = `-- name: UpdateCalendarEvent :one
UPDATE calendar_events
SET
    title = ?,
    description = ?,
    start_time = ?,
    end_time = ?,
    all_day = ?,
    location = ?,
    calendar_id = ?
WHERE
    id = ? RETURNING id, title, description, start_time, end_time, all_day, location, calendar_id
`

type UpdateCalendarEventParams struct {
	Title       string
	Description sql.NullString
	StartTime   time.Time
	EndTime     sql.NullTime
	AllDay      bool
	Location    string
	CalendarID  int64
	ID          int64
}

func (q *Queries) UpdateCalendarEvent(ctx context.Context, arg UpdateCalendarEventParams) (CalendarEvent, error) {
	row := q.db.QueryRowContext(ctx, updateCalendarEvent,
		arg.Title,
		arg.Description,
		arg.StartTime,
		arg.EndTime,
		arg.AllDay,
		arg.Location,
		arg.CalendarID,
		arg.ID,
	)
	var i CalendarEvent
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.StartTime,
		&i.EndTime,
		&i.AllDay,
		&i.Location,
		&i.CalendarID,
	)
	return i, err
}
