// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: calendars.sql

package db

import (
	"context"
)

const createCalendar = `-- name: CreateCalendar :one
INSERT INTO
    calendars (name)
VALUES
    (?) RETURNING id, name
`

func (q *Queries) CreateCalendar(ctx context.Context, name string) (Calendar, error) {
	row := q.db.QueryRowContext(ctx, createCalendar, name)
	var i Calendar
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const deleteCalendar = `-- name: DeleteCalendar :exec
DELETE FROM calendars
WHERE
    id = ?
`

func (q *Queries) DeleteCalendar(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteCalendar, id)
	return err
}

const getCalendar = `-- name: GetCalendar :one
SELECT
    id, name
FROM
    calendars
WHERE
    id = ?
LIMIT
    1
`

func (q *Queries) GetCalendar(ctx context.Context, id int64) (Calendar, error) {
	row := q.db.QueryRowContext(ctx, getCalendar, id)
	var i Calendar
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const listCalendars = `-- name: ListCalendars :many
SELECT
    id, name
FROM
    calendars
ORDER BY
    name
`

func (q *Queries) ListCalendars(ctx context.Context) ([]Calendar, error) {
	rows, err := q.db.QueryContext(ctx, listCalendars)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Calendar
	for rows.Next() {
		var i Calendar
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCalendar = `-- name: UpdateCalendar :one
UPDATE calendars
SET
    name = ?
WHERE
    id = ? RETURNING id, name
`

type UpdateCalendarParams struct {
	Name string
	ID   int64
}

func (q *Queries) UpdateCalendar(ctx context.Context, arg UpdateCalendarParams) (Calendar, error) {
	row := q.db.QueryRowContext(ctx, updateCalendar, arg.Name, arg.ID)
	var i Calendar
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}
