// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: inventory.sql

package db

import (
	"context"
)

const createInventory = `-- name: CreateInventory :one
INSERT INTO
    inventory (name, amount, unit)
VALUES
    (?, ?, ?) RETURNING id, name, amount, unit
`

type CreateInventoryParams struct {
	Name   string
	Amount float64
	Unit   string
}

func (q *Queries) CreateInventory(ctx context.Context, arg CreateInventoryParams) (Inventory, error) {
	row := q.db.QueryRowContext(ctx, createInventory, arg.Name, arg.Amount, arg.Unit)
	var i Inventory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Amount,
		&i.Unit,
	)
	return i, err
}

const deleteInventory = `-- name: DeleteInventory :exec
DELETE FROM inventory
WHERE
    id = ?
`

func (q *Queries) DeleteInventory(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteInventory, id)
	return err
}

const getInventory = `-- name: GetInventory :one
SELECT
    id, name, amount, unit
FROM
    inventory
WHERE
    id = ?
LIMIT
    1
`

func (q *Queries) GetInventory(ctx context.Context, id int64) (Inventory, error) {
	row := q.db.QueryRowContext(ctx, getInventory, id)
	var i Inventory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Amount,
		&i.Unit,
	)
	return i, err
}

const getInventoryByName = `-- name: GetInventoryByName :one
SELECT
    id, name, amount, unit
FROM
    inventory
WHERE
    name = ?
LIMIT
    1
`

func (q *Queries) GetInventoryByName(ctx context.Context, name string) (Inventory, error) {
	row := q.db.QueryRowContext(ctx, getInventoryByName, name)
	var i Inventory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Amount,
		&i.Unit,
	)
	return i, err
}

const listInventories = `-- name: ListInventories :many
SELECT
    id, name, amount, unit
FROM
    inventory
ORDER BY
    name
`

func (q *Queries) ListInventories(ctx context.Context) ([]Inventory, error) {
	rows, err := q.db.QueryContext(ctx, listInventories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Inventory
	for rows.Next() {
		var i Inventory
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Amount,
			&i.Unit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInventory = `-- name: UpdateInventory :one
UPDATE inventory
SET
    name = ?,
    amount = ?,
    unit = ?
WHERE
    id = ? RETURNING id, name, amount, unit
`

type UpdateInventoryParams struct {
	Name   string
	Amount float64
	Unit   string
	ID     int64
}

func (q *Queries) UpdateInventory(ctx context.Context, arg UpdateInventoryParams) (Inventory, error) {
	row := q.db.QueryRowContext(ctx, updateInventory,
		arg.Name,
		arg.Amount,
		arg.Unit,
		arg.ID,
	)
	var i Inventory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Amount,
		&i.Unit,
	)
	return i, err
}
