// Package swagger Code generated by swaggo/swag. DO NOT EDIT
package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/google/authorize": {
            "get": {
                "description": "Returns an authorization URL and state token for starting OAuth flow",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Get Google authorization URL",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/serverutil.Response"
                        }
                    }
                }
            }
        },
        "/auth/google/callback": {
            "get": {
                "description": "Callback endpoint used by Google OAuth. Exchanges code for token and returns HTML.",
                "tags": [
                    "auth"
                ],
                "summary": "Google OAuth callback",
                "parameters": [
                    {
                        "type": "string",
                        "description": "OAuth state token",
                        "name": "state",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Authorization code",
                        "name": "code",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "HTML page",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/serverutil.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/serverutil.Response"
                        }
                    }
                }
            }
        },
        "/auth/google/disconnect": {
            "post": {
                "description": "Removes stored Google OAuth token for a user (or all tokens if no email provided)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Disconnect Google account",
                "parameters": [
                    {
                        "description": "{email: string}",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/auth/login": {
            "post": {
                "description": "Authenticates with username and password, returns a session token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Login",
                "parameters": [
                    {
                        "description": "{username, password}",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/serverutil.Response"
                        }
                    }
                }
            }
        },
        "/auth/logout": {
            "post": {
                "description": "Invalidates the current session",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Logout",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/auth/recover": {
            "post": {
                "description": "Resets password using recovery phrase",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Recover account",
                "parameters": [
                    {
                        "description": "{recoveryPhrase, newPassword}",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/serverutil.Response"
                        }
                    }
                }
            }
        },
        "/auth/setup": {
            "post": {
                "description": "Creates the owner account. Can only be called once.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "First-boot user setup",
                "parameters": [
                    {
                        "description": "{username, password}",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/serverutil.Response"
                        }
                    }
                }
            }
        },
        "/auth/status": {
            "get": {
                "description": "Returns whether initial setup has been completed",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Check auth setup status",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/books": {
            "get": {
                "description": "Finds all books in the cirrus directory",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "books"
                ],
                "summary": "List books",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/v1_books.BookJSON"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/serverutil.Response"
                        }
                    }
                }
            }
        },
        "/cirrus": {
            "get": {
                "description": "merges files across all managed devices for the given filePath. If deviceSerial is empty, list files across all devices. Otherwise, only for the specified device",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cirrus"
                ],
                "summary": "Lists files",
                "parameters": [
                    {
                        "type": "string",
                        "description": "File dir to list",
                        "name": "rootDir",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Device serial number to filter by",
                        "name": "serial",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/v1_files.FileNodeJSON"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/serverutil.Response"
                        }
                    }
                }
            },
            "put": {
                "description": "Enqueue a file move operation between paths/devices",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cirrus"
                ],
                "summary": "Move or rename a file",
                "parameters": [
                    {
                        "description": "Move file request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1_files.moveFileRequest"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Ok",
                        "schema": {
                            "$ref": "#/definitions/serverutil.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/serverutil.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/serverutil.Response"
                        }
                    }
                }
            },
            "delete": {
                "description": "Enqueue deletion of files under the specified root directory",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cirrus"
                ],
                "summary": "Delete files",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Root directory",
                        "name": "rootDir",
                        "in": "query"
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "csv",
                        "description": "Array of file paths to delete",
                        "name": "filePaths",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Device serial number to filter by",
                        "name": "serial",
                        "in": "query"
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Ok",
                        "schema": {
                            "$ref": "#/definitions/serverutil.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/serverutil.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/serverutil.Response"
                        }
                    }
                }
            }
        },
        "/cirrus/download": {
            "get": {
                "description": "Downloads a single file or zips a folder and streams it back to the client",
                "produces": [
                    "application/octet-stream"
                ],
                "tags": [
                    "cirrus"
                ],
                "summary": "Download a file or folder",
                "parameters": [
                    {
                        "type": "string",
                        "description": "File path to download",
                        "name": "filePath",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Device serial number to filter by",
                        "name": "serial",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/serverutil.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/serverutil.Response"
                        }
                    }
                }
            }
        },
        "/cirrus/folder/{folderDir}": {
            "post": {
                "description": "Enqueue create-folder operation under the given folder directory",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cirrus"
                ],
                "summary": "Create a new folder",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Folder directory",
                        "name": "folderDir",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Name of the new folder",
                        "name": "folderName",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Device serial number to create folder on",
                        "name": "serial",
                        "in": "query"
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Ok",
                        "schema": {
                            "$ref": "#/definitions/serverutil.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/serverutil.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/serverutil.Response"
                        }
                    }
                }
            }
        },
        "/cirrus/recent": {
            "get": {
                "description": "Returns files sorted by modification time (newest first) across all managed devices.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cirrus"
                ],
                "summary": "List recently uploaded files",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Maximum number of files to return (default 20, max 200)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "csv",
                        "description": "Filter by device serial(s)",
                        "name": "serial",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/v1_files.FileNodeWithTimeJSON"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/serverutil.Response"
                        }
                    }
                }
            }
        },
        "/cirrus/search": {
            "get": {
                "description": "searches for a file across all managed devices for the given search term. If deviceSerial is empty, search across all devices. Otherwise, only for the specified device",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cirrus"
                ],
                "summary": "Searches for files",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Search term to find",
                        "name": "query",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Device serial number to filter by",
                        "name": "serial",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/v1_files.FileNodeJSON"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/serverutil.Response"
                        }
                    }
                }
            }
        },
        "/cirrus/upload": {
            "post": {
                "description": "Upload one or more files via multipart/form-data",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cirrus"
                ],
                "summary": "Upload files to the top-level directory",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Device serial number to upload to",
                        "name": "serial",
                        "in": "query"
                    },
                    {
                        "type": "file",
                        "description": "File to upload",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/serverutil.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/serverutil.Response"
                        }
                    }
                }
            }
        },
        "/cirrus/upload/{rootDir}": {
            "post": {
                "description": "Upload one or more files via multipart/form-data",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cirrus"
                ],
                "summary": "Upload files to a nested directory",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Directory to upload into",
                        "name": "rootDir",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Device serial number to upload to",
                        "name": "serial",
                        "in": "query"
                    },
                    {
                        "type": "file",
                        "description": "File to upload",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/serverutil.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/serverutil.Response"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Returns current hardware health: CPU, memory, disk usage and temperature. Sets healthy=false with alert messages when any metric exceeds its critical threshold.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Get system health status",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1_health.HealthJSON"
                        }
                    }
                }
            }
        },
        "/migration/google/start": {
            "post": {
                "description": "Starts an import job for selected Google services for the given email",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "migration"
                ],
                "summary": "Start Google import/migration",
                "parameters": [
                    {
                        "description": "Start import request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1_migration.StartImportRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/serverutil.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/serverutil.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/serverutil.Response"
                        }
                    }
                }
            }
        },
        "/migration/google/status/{jobId}": {
            "get": {
                "description": "Returns the status of a previously started import job",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "migration"
                ],
                "summary": "Get Google import job status",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Job ID",
                        "name": "jobId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/serverutil.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/serverutil.Response"
                        }
                    }
                }
            }
        },
        "/photos": {
            "get": {
                "description": "Finds all photos across all managed devices with pagination support.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "photos"
                ],
                "summary": "List photos",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Pagination offset (default 0)",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page size (default 50, max 200)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Device serial to filter by",
                        "name": "serial",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1_photos.PaginatedPhotosResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/serverutil.Response"
                        }
                    }
                }
            }
        },
        "/sbom": {
            "get": {
                "description": "Returns the Go version and all embedded dependency information from the compiled binary",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "version"
                ],
                "summary": "Get software bill of materials",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1_version.SbomJSON"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/serverutil.Response"
                        }
                    }
                }
            }
        },
        "/storage/devices/backup": {
            "post": {
                "description": "Begin a backup to a device",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "storage"
                ],
                "summary": "Do a one-time backup to a device",
                "parameters": [
                    {
                        "description": "Backup parameters",
                        "name": "backupParams",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/storageutil.BackupToDeviceParams"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/serverutil.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/serverutil.Response"
                        }
                    }
                }
            }
        },
        "/storage/devices/rename": {
            "patch": {
                "description": "Sets a custom display name for a storage device identified by its device path",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "storage"
                ],
                "summary": "Rename a storage device",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Device path (e.g. /dev/disk3s5 — leading slash included in wildcard)",
                        "name": "devicePath",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "{name: string}",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/serverutil.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/serverutil.Response"
                        }
                    }
                }
            }
        },
        "/storage/devices/status": {
            "get": {
                "description": "Returns statuses for all known storage devices",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "storage"
                ],
                "summary": "List storage device statuses",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/serverutil.Response"
                        }
                    }
                }
            }
        },
        "/storage/devices/status/{serial}": {
            "get": {
                "description": "Returns status for a single storage device identified by serial",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "storage"
                ],
                "summary": "Get storage device status by serial",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Device serial",
                        "name": "serial",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/serverutil.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/serverutil.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/serverutil.Response"
                        }
                    }
                }
            }
        },
        "/storage/devices/usb/{serial}": {
            "post": {
                "description": "Mounts a USB storage device identified by serial and returns mount info",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "storage"
                ],
                "summary": "Enable (mount) a USB storage device",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Device serial",
                        "name": "serial",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/serverutil.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/serverutil.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/serverutil.Response"
                        }
                    }
                }
            },
            "delete": {
                "description": "Unmounts a USB storage device identified by serial",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "storage"
                ],
                "summary": "Disable (unmount) a USB storage device",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Device serial",
                        "name": "serial",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/serverutil.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/serverutil.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/serverutil.Response"
                        }
                    }
                }
            }
        },
        "/version": {
            "get": {
                "description": "Retrieves the installed version of the application",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "version"
                ],
                "summary": "Get installed version",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1_version.VersionJSON"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/serverutil.Response"
                        }
                    }
                }
            }
        },
        "/version/available": {
            "get": {
                "description": "Lists all available versions for update",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "version"
                ],
                "summary": "List available versions",
                "parameters": [
                    {
                        "type": "boolean",
                        "description": "Include all versions, including old and development versions",
                        "name": "all",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of available versions",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/updateutil.UpdateVersion"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/serverutil.Response"
                        }
                    }
                }
            }
        },
        "/version/latest": {
            "get": {
                "description": "Retrieves the latest available version of the application",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "version"
                ],
                "summary": "Get latest version",
                "responses": {
                    "200": {
                        "description": "Latest version information",
                        "schema": {
                            "$ref": "#/definitions/updateutil.UpdateVersion"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/serverutil.Response"
                        }
                    }
                }
            },
            "post": {
                "description": "Finds and installs the latest version",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "version"
                ],
                "summary": "Update to the latest version",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1_version.UpdateRequest"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/serverutil.Response"
                        }
                    }
                }
            }
        },
        "/version/update": {
            "post": {
                "description": "Performs an update to the specified version",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "version"
                ],
                "summary": "Perform update",
                "parameters": [
                    {
                        "description": "Update Request",
                        "name": "update",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1_version.UpdateParams"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1_version.UpdateRequest"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/serverutil.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/serverutil.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "serverutil.ContentType": {
            "type": "string",
            "enum": [
                "text/html",
                "application/json"
            ],
            "x-enum-varnames": [
                "ContentTypeHTML",
                "ContentTypeJSON"
            ]
        },
        "serverutil.Response": {
            "type": "object",
            "properties": {
                "contentType": {
                    "$ref": "#/definitions/serverutil.ContentType"
                },
                "data": {},
                "error": {},
                "statusCode": {
                    "type": "integer"
                }
            }
        },
        "storageutil.BackupToDeviceParams": {
            "type": "object",
            "properties": {
                "sourceDeviceSerial": {
                    "type": "string"
                },
                "targetDeviceSerial": {
                    "type": "string"
                }
            }
        },
        "updateutil.UpdateSource": {
            "type": "object",
            "properties": {
                "account": {
                    "type": "string"
                },
                "kind": {
                    "$ref": "#/definitions/updateutil.UpdateSourceKind"
                },
                "path": {
                    "type": "string"
                }
            }
        },
        "updateutil.UpdateSourceKind": {
            "type": "string",
            "enum": [
                "azure",
                "github"
            ],
            "x-enum-varnames": [
                "UpdateSourceKindAzure",
                "UpdateSourceKindGithub"
            ]
        },
        "updateutil.UpdateVersion": {
            "type": "object",
            "properties": {
                "url": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "v1_books.BookJSON": {
            "type": "object",
            "properties": {
                "fileName": {
                    "type": "string"
                },
                "mtime": {
                    "type": "integer"
                },
                "relPath": {
                    "type": "string"
                },
                "size": {
                    "type": "integer"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "v1_files.FileNodeJSON": {
            "type": "object",
            "properties": {
                "deviceName": {
                    "type": "string"
                },
                "devicePath": {
                    "type": "string"
                },
                "deviceSerial": {
                    "type": "string"
                },
                "dirPath": {
                    "description": "Directory path containing the file, for easier client-side handling",
                    "type": "string"
                },
                "fullPath": {
                    "type": "string"
                },
                "isDir": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "size": {
                    "type": "integer"
                }
            }
        },
        "v1_files.FileNodeWithTimeJSON": {
            "type": "object",
            "properties": {
                "deviceName": {
                    "type": "string"
                },
                "devicePath": {
                    "type": "string"
                },
                "deviceSerial": {
                    "type": "string"
                },
                "dirPath": {
                    "description": "Directory path containing the file, for easier client-side handling",
                    "type": "string"
                },
                "fullPath": {
                    "type": "string"
                },
                "isDir": {
                    "type": "boolean"
                },
                "modifiedAt": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "size": {
                    "type": "integer"
                }
            }
        },
        "v1_files.moveFileRequest": {
            "type": "object",
            "properties": {
                "newDeviceSerial": {
                    "type": "string"
                },
                "newFilePath": {
                    "type": "string"
                },
                "oldDeviceSerial": {
                    "type": "string"
                },
                "oldFilePath": {
                    "type": "string"
                }
            }
        },
        "v1_health.HealthJSON": {
            "type": "object",
            "properties": {
                "alerts": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "cpuCoreCount": {
                    "type": "integer"
                },
                "cpuCorePercents": {
                    "type": "array",
                    "items": {
                        "type": "number"
                    }
                },
                "cpuPercent": {
                    "type": "number"
                },
                "diskPercent": {
                    "type": "number"
                },
                "diskTotalBytes": {
                    "type": "integer"
                },
                "diskUsedBytes": {
                    "type": "integer"
                },
                "healthy": {
                    "type": "boolean"
                },
                "hostname": {
                    "description": "Hostname is the OS hostname of the butler device.\nClients can use this to display accurate LAN mount paths (e.g. smb://hostname.local).",
                    "type": "string"
                },
                "memPercent": {
                    "type": "number"
                },
                "memTotalBytes": {
                    "type": "integer"
                },
                "memUsedBytes": {
                    "type": "integer"
                },
                "temperatureCelsius": {
                    "type": "number"
                }
            }
        },
        "v1_migration.StartImportRequest": {
            "type": "object",
            "properties": {
                "deviceSerial": {
                    "description": "Optional: empty string for internal drive",
                    "type": "string"
                },
                "email": {
                    "description": "User's Google email",
                    "type": "string"
                },
                "services": {
                    "type": "object",
                    "properties": {
                        "calendar": {
                            "description": "UNUSED: calendar migration is not yet implemented (see #856)",
                            "type": "boolean"
                        },
                        "contacts": {
                            "type": "boolean"
                        },
                        "drive": {
                            "type": "boolean"
                        },
                        "photos": {
                            "type": "boolean"
                        }
                    }
                }
            }
        },
        "v1_photos.PaginatedPhotosResponse": {
            "type": "object",
            "properties": {
                "limit": {
                    "type": "integer"
                },
                "offset": {
                    "type": "integer"
                },
                "photos": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/v1_photos.PhotoJSON"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "v1_photos.PhotoJSON": {
            "type": "object",
            "properties": {
                "fileName": {
                    "type": "string"
                },
                "mtime": {
                    "type": "integer"
                },
                "relPath": {
                    "type": "string"
                },
                "serial": {
                    "type": "string"
                },
                "size": {
                    "type": "integer"
                }
            }
        },
        "v1_version.SbomDependencyJSON": {
            "type": "object",
            "properties": {
                "path": {
                    "type": "string"
                },
                "replace": {
                    "$ref": "#/definitions/v1_version.SbomDependencyJSON"
                },
                "sum": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "v1_version.SbomJSON": {
            "type": "object",
            "properties": {
                "dependencies": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/v1_version.SbomDependencyJSON"
                    }
                },
                "goVersion": {
                    "type": "string"
                },
                "main": {
                    "$ref": "#/definitions/v1_version.SbomModuleJSON"
                }
            }
        },
        "v1_version.SbomModuleJSON": {
            "type": "object",
            "properties": {
                "path": {
                    "type": "string"
                },
                "sum": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "v1_version.UpdateParams": {
            "type": "object",
            "properties": {
                "branch": {
                    "type": "string"
                },
                "force": {
                    "type": "boolean"
                },
                "source": {
                    "$ref": "#/definitions/updateutil.UpdateSource"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "v1_version.UpdateRequest": {
            "type": "object",
            "properties": {
                "version": {
                    "type": "string"
                }
            }
        },
        "v1_version.VersionJSON": {
            "type": "object",
            "properties": {
                "buildDate": {
                    "type": "string"
                },
                "gitCommit": {
                    "type": "string"
                },
                "goVersion": {
                    "type": "string"
                },
                "semver": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
