FROM postgres:17.2

# Set environment variables
ENV POSTGRES_DB=dotai
ENV POSTGRES_USER=admin
ENV POSTGRES_PASSWORD=admin

# Expose the PostgreSQL port
EXPOSE 5432

# Set the default command to run PostgreSQL
CMD ["postgres"]
