name: data_table_example_spreadsheet
description: Example spreadsheet for data_table package
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  data_table:
    path: ../..

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
