name: data_table
description: Pure Dart data table engine (headless) for Flutter.
version: 0.0.1
environment:
  sdk: ^3.6.0

resolution: workspace

publish_to: none

dependencies:
  flutter:
    sdk: flutter
  quark_formula:
    path: ../quark_formula
  quark_icons:
    path: ../quark_icons

dev_dependencies:
  flutter_test:
    sdk: flutter
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms: {}
