// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.943
package epub_viewer

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "path/filepath"

func Component(filePath string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"file-viewer-epub\" style=\"width: 80vw; height: 60vh;\"><div class=\"file-viewer-epub-controls\"><div style=\"margin-bottom: var(--spacing-lg);\"><button id=\"book-reader-prev\" class=\"file-viewer-epub-btn\">Previous Page</button> <button id=\"book-reader-next\" class=\"file-viewer-epub-btn\">Next Page</button></div><div id=\"book-reader\"></div></div></div><script>\n\t\tvar navigationListener = null;\n\t\tvar fileViewerContent = document.getElementById('file-viewer-content');\n\t\tvar loadedBook = ePub(")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var2, templ_7745c5c3_Err := templruntime.ScriptContentOutsideStringLiteral(filepath.Join("/api/v1/files", filePath))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/server/ui/components/file_explorer/file_viewer/epub_viewer/component.templ`, Line: 27, Col: 67}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var2)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, ");\n        var rendition = loadedBook.renderTo(\"book-reader\", {\n            method: \"default\",\n            flow: \"paginated\",\n            width: '80vw',\n            height: '60vh',\n        });\n        var prevButton = document.getElementById('book-reader-prev');\n        var nextButton = document.getElementById('book-reader-next');\n        prevButton.addEventListener('click', () => {\n            rendition.prev();\n        });\n        nextButton.addEventListener('click', () => {\n            rendition.next();\n        });\n        navigationListener = (event) => {\n            switch (event.key) {\n                case 'ArrowLeft':\n                    rendition.prev();\n                    break;\n                case 'Enter':\n                case 'ArrowRight':\n                    rendition.next();\n                    break;\n                default:\n                    break;\n            }\n        };\n        addEventListener('keydown', navigationListener);\n        fileViewerContent.focus();\n        var displayed = rendition.display();\n        if (displayed) {\n            displayed.then(() => {}).catch((error) => {\n                fileViewerContent.innerHTML = `<p>Error loading book: ${error}</p>`;\n            });\n        } else {\n            fileViewerContent.innerHTML = `<p>Error displaying book.</p>`;\n        }\n\t</script>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
