name: autobutler_icons_example_icon_gallery
description: Browseable icon gallery for the autobutler_icons package.
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  autobutler_icons:
    path: ../..

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
