// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.943
package health

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "autobutler/internal/server/ui/types"

func Component(pageState types.PageState) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"health-container\"><h1 class=\"health-title\">Health Dashboard</h1><!-- Tab Navigation --><div class=\"health-tabs\"><button class=\"tab-button active\" data-tab=\"errors\">Errors</button> <button class=\"tab-button\" data-tab=\"latency\">Latency</button> <button class=\"tab-button\" data-tab=\"traffic\">Traffic</button> <button class=\"tab-button\" data-tab=\"saturation\">Saturation</button></div><!-- Tab Content --><div class=\"tab-content active\" data-content=\"errors\"><div class=\"chart-container\"><canvas id=\"errorsPageChart\"></canvas></div><div class=\"chart-container\"><canvas id=\"errorsApiChart\"></canvas></div></div><div class=\"tab-content\" data-content=\"latency\"><div class=\"chart-container\"><canvas id=\"latencyPageChart\"></canvas></div><div class=\"chart-container\"><canvas id=\"latencyApiChart\"></canvas></div><div class=\"chart-container\"><canvas id=\"latencyPageP99Chart\"></canvas></div><div class=\"chart-container\"><canvas id=\"latencyApiP99Chart\"></canvas></div></div><div class=\"tab-content\" data-content=\"traffic\"><div class=\"chart-container\"><canvas id=\"trafficPageChart\"></canvas></div><div class=\"chart-container\"><canvas id=\"trafficApiChart\"></canvas></div></div><div class=\"tab-content\" data-content=\"saturation\"><div class=\"chart-container\"><canvas id=\"saturationChart\"></canvas></div></div></div><script>\n\t\tinitializeHealthTabs();\n\t\tcreateGoldenSignalCharts();\n\t</script>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
