// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.943
package health

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "autobutler/internal/server/ui/types"

func Component(pageState types.PageState) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div style=\"display: flex; flex-direction: column; gap: 20px; padding: 20px;\"><h1 style=\"color: #FFF; margin: 0 0 10px 0; font-size: 32px; font-weight: 600;\">Health Dashboard</h1><p style=\"color: rgba(255, 255, 255, 0.7); margin: 0 0 20px 0; font-size: 16px;\">Golden signals monitoring for application health and performance</p><div style=\"background: rgba(0, 0, 0, 0.2); padding: 15px; border-radius: 8px;\"><canvas id=\"latencyPageChart\"></canvas></div><div style=\"background: rgba(0, 0, 0, 0.2); padding: 15px; border-radius: 8px;\"><canvas id=\"latencyApiChart\"></canvas></div><div style=\"background: rgba(0, 0, 0, 0.2); padding: 15px; border-radius: 8px;\"><canvas id=\"trafficPageChart\"></canvas></div><div style=\"background: rgba(0, 0, 0, 0.2); padding: 15px; border-radius: 8px;\"><canvas id=\"trafficApiChart\"></canvas></div><div style=\"background: rgba(0, 0, 0, 0.2); padding: 15px; border-radius: 8px;\"><canvas id=\"saturationChart\"></canvas></div></div><script>\n\t\t\tcreateGoldenSignalCharts();\n\t\t</script>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
