#! /usr/bin/bash

set -euo pipefail

sudo apt-get update -y
sudo apt-get install -y \
	vim \
	git \
	curl \
	python3 \
	python3-pip \
	pipx \
	gh \
	cgroupfs-mount

curl --fail https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

curl --version
git --version
helm version
python3 --version
python3 -m pip --version
python3 -m pipx --version
vim --version

python3 -m pipx ensurepath
python3 -m pipx install --include-deps ansible

ORG=exokomodo
REPO=exoflow
ORG_LOCAL=${HOME}/github.com/${ORG}
REPO_LOCAL=${ORG_LOCAL}/${REPO}
mkdir -p ${ORG_LOCAL}
if ! [[ -d "${REPO_LOCAL}" ]]; then
	echo "Login with 'gh auth login'"
	gh repo clone \
		${ORG}/${REPO} \
		${REPO_LOCAL} \
		-- --recurse-submodules
fi

if command -v docker >> /dev/null; then
	echo "Skipping docker installation...already installed"
else
	${REPO_LOCAL}/src/autobutler/infra/install_docker_pi.sh
fi

sudo swapoff -a
CGROUP_ARGS="cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory"
if ! grep "${CGROUP_ARGS}" /boot/firmware/cmdline.txt; then
	sudo bash -c "echo '${CGROUP_ARGS}' >> /boot/firmware/cmdline.txt"
	echo "Rebooting in 5 seconds..."
	sleep 5
	sudo shutdown -r now
fi

if ! [[ -f "${HOME}/.kube/config" ]]; then
	pushd ${REPO_LOCAL}/src/autobutler/infra/ansible
	ansible-playbook -i inventory/hosts ./playbooks/test_connection.yml
	ansible-playbook -i inventory/hosts ./playbooks/install_k3s.yml
	popd
fi

helm repo add \
	kubernetes-dashboard \
	https://kubernetes.github.io/dashboard/
helm upgrade \
	--install kubernetes-dashboard \
	kubernetes-dashboard/kubernetes-dashboard \
	--create-namespace \
	--namespace kubernetes-dashboard
echo 'To access the dashboard: kubectl -n kubernetes-dashboard port-forward svc/kubernetes-dashboard-kong-proxy 8443:443'
