// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.898
package file_explorer

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func scripts() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<script>\n    var contextMenuPosition = {\n        x: null,\n        y: null,\n    }\n    function showFileInfo(event, fileName) {\n        alert(fileName);\n    }\n\n    function toggleContextMenu(event, parentNode) {\n        if (event) {\n            event.preventDefault();\n            event.stopPropagation();\n        }\n        const contextMenu = parentNode.querySelector('.context-menu');\n        contextMenu.style.left = null;\n        contextMenu.style.top = null;\n        contextMenu.classList.toggle('hidden');\n        return contextMenu;\n    }\n\n    function toggleFloatingContextMenu(event, parentNode) {\n        const contextMenu = toggleContextMenu(event, parentNode);\n        console.log(event.clientX, event.clientY);\n        contextMenu.style.left = `${event.clientX}px`;\n        contextMenu.style.top = `${event.clientY}px`;\n    }\n    </script>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
