// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package file_context_menu

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"autobutler/pkg/ui/components/lib"
	"autobutler/pkg/ui/types"
	"autobutler/pkg/util/fileutil"
	"autobutler/pkg/util/maputil"
	"fmt"
	"path/filepath"
)

func Component(pageState types.PageState, file *fileutil.DeviceFileInfo) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div><button class=\"context-menu-trigger\" onclick=\"window.ab.toggleFloatingContextMenu(event, this.parentElement)\" aria-label=\"Open context menu\" type=\"button\" tabindex=\"0\">&#x22EE;</button>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		items := maputil.NewOrderedMapFromValues(
			[]string{"Download", "Move/Rename", "File Details", "Delete"},
			[]*lib.ContextMenuHandlerProps{
				{
					OnClickHandler: fmt.Sprintf("window.ab.closeContextMenuFromItem(event); window.ab.fileExplorer.downloadFile('%s');", filepath.Join(`/api/v1/files`, pageState.RootDir, file.Name())),
				},
				{
					OnClickHandler: fmt.Sprintf("window.ab.closeContextMenuFromItem(event); window.ab.fileExplorer.moveFile(event, '%s', '%s');", pageState.RootDir, file.Name()),
				},
				{
					OnClickHandler: fmt.Sprintf("window.ab.closeContextMenuFromItem(event); window.ab.fileExplorer.showFileDetails('%s');", file.Name()),
				},
				{
					AdditionalClasses: "context-menu-item--danger",
					ButtonAttributes: templ.Attributes{
						"hx-target": "#file-explorer",
						"hx-swap":   "outerHTML",
						"hx-delete": filepath.Join(`/api/v1/files`),
						"hx-vals":   fmt.Sprintf(`{"rootDir":"%s", "filePaths":["%s"]}`, pageState.RootDir, file.Name()),
					},
				},
			},
		)
		templ_7745c5c3_Err = lib.ContextMenu(items, false).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
