// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: instance.sql

package db

import (
	"context"
)

const getInstanceID = `-- name: GetInstanceID :one
SELECT instance_id FROM instance WHERE id = 1 LIMIT 1
`

func (q *Queries) GetInstanceID(ctx context.Context) (string, error) {
	row := q.db.QueryRowContext(ctx, getInstanceID)
	var instance_id string
	err := row.Scan(&instance_id)
	return instance_id, err
}

const insertInstanceID = `-- name: InsertInstanceID :exec
INSERT OR IGNORE INTO instance (id, instance_id) VALUES (1, ?)
`

func (q *Queries) InsertInstanceID(ctx context.Context, instanceID string) error {
	_, err := q.db.ExecContext(ctx, insertInstanceID, instanceID)
	return err
}
