// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type ConnectedDevice struct {
	ID           int64
	IpAddress    string
	UserAgent    string
	FirstSeenAt  time.Time
	LastSeenAt   time.Time
	RequestCount int64
}

type DeviceName struct {
	DevicePath  string
	DisplayName string
	UpdatedAt   time.Time
}

type PhotoAlbum struct {
	ID        int64
	Name      string
	ParentID  sql.NullInt64
	CreatedAt time.Time
	UpdatedAt time.Time
}

type PhotoAlbumItem struct {
	ID           int64
	AlbumID      int64
	DeviceSerial string
	RelPath      string
	AddedAt      time.Time
}

type Session struct {
	Token     string
	UserID    int64
	ExpiresAt time.Time
	CreatedAt time.Time
}

type User struct {
	ID                 int64
	Username           string
	PasswordHash       string
	RecoveryPhraseHash string
	CreatedAt          time.Time
}
