// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pairing.sql

package db

import (
	"context"
	"database/sql"
)

const consumePairingToken = `-- name: ConsumePairingToken :exec
UPDATE pairing_tokens
SET used_at = datetime('now')
WHERE token_hash = ?
`

func (q *Queries) ConsumePairingToken(ctx context.Context, tokenHash string) error {
	_, err := q.db.ExecContext(ctx, consumePairingToken, tokenHash)
	return err
}

const createPairingToken = `-- name: CreatePairingToken :exec
INSERT INTO pairing_tokens (token_hash, created_by)
VALUES (?, ?)
`

type CreatePairingTokenParams struct {
	TokenHash string
	CreatedBy sql.NullInt64
}

func (q *Queries) CreatePairingToken(ctx context.Context, arg CreatePairingTokenParams) error {
	_, err := q.db.ExecContext(ctx, createPairingToken, arg.TokenHash, arg.CreatedBy)
	return err
}

const getPairingToken = `-- name: GetPairingToken :one
SELECT id, token_hash, created_by, expires_at, used_at FROM pairing_tokens
WHERE token_hash = ?
  AND expires_at > datetime('now')
  AND used_at IS NULL
LIMIT 1
`

func (q *Queries) GetPairingToken(ctx context.Context, tokenHash string) (PairingToken, error) {
	row := q.db.QueryRowContext(ctx, getPairingToken, tokenHash)
	var i PairingToken
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.CreatedBy,
		&i.ExpiresAt,
		&i.UsedAt,
	)
	return i, err
}

const purgePairingTokens = `-- name: PurgePairingTokens :exec
DELETE FROM pairing_tokens
WHERE expires_at <= datetime('now') OR used_at IS NOT NULL
`

func (q *Queries) PurgePairingTokens(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, purgePairingTokens)
	return err
}
