// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: photo_rotations.sql

package db

import (
	"context"
)

const deletePhotoRotation = `-- name: DeletePhotoRotation :exec
DELETE FROM photo_rotations
WHERE
    device_serial = ?
    AND rel_path = ?
`

type DeletePhotoRotationParams struct {
	DeviceSerial string
	RelPath      string
}

func (q *Queries) DeletePhotoRotation(ctx context.Context, arg DeletePhotoRotationParams) error {
	_, err := q.db.ExecContext(ctx, deletePhotoRotation, arg.DeviceSerial, arg.RelPath)
	return err
}

const getPhotoRotation = `-- name: GetPhotoRotation :one
SELECT
    rotation_quarters
FROM
    photo_rotations
WHERE
    device_serial = ?
    AND rel_path = ?
LIMIT
    1
`

type GetPhotoRotationParams struct {
	DeviceSerial string
	RelPath      string
}

func (q *Queries) GetPhotoRotation(ctx context.Context, arg GetPhotoRotationParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getPhotoRotation, arg.DeviceSerial, arg.RelPath)
	var rotation_quarters int64
	err := row.Scan(&rotation_quarters)
	return rotation_quarters, err
}

const upsertPhotoRotation = `-- name: UpsertPhotoRotation :exec
INSERT INTO
    photo_rotations (device_serial, rel_path, rotation_quarters, updated_at)
VALUES
    (?, ?, ?, datetime('now'))
ON CONFLICT (device_serial, rel_path) DO UPDATE SET
    rotation_quarters = excluded.rotation_quarters,
    updated_at = excluded.updated_at
`

type UpsertPhotoRotationParams struct {
	DeviceSerial     string
	RelPath          string
	RotationQuarters int64
}

func (q *Queries) UpsertPhotoRotation(ctx context.Context, arg UpsertPhotoRotationParams) error {
	_, err := q.db.ExecContext(ctx, upsertPhotoRotation, arg.DeviceSerial, arg.RelPath, arg.RotationQuarters)
	return err
}
