// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: photo_hashes.sql

package db

import (
	"context"
	"database/sql"
)

const listExactDuplicates = `-- name: ListExactDuplicates :many
SELECT content_hash, device_serial, rel_path
FROM photo_hashes
WHERE content_hash IS NOT NULL
  AND content_hash IN (
      SELECT content_hash FROM photo_hashes
      WHERE content_hash IS NOT NULL
      GROUP BY content_hash HAVING COUNT(*) > 1
  )
ORDER BY content_hash, device_serial, rel_path
`

type ListExactDuplicatesRow struct {
	ContentHash  sql.NullString
	DeviceSerial string
	RelPath      string
}

func (q *Queries) ListExactDuplicates(ctx context.Context) ([]ListExactDuplicatesRow, error) {
	rows, err := q.db.QueryContext(ctx, listExactDuplicates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExactDuplicatesRow
	for rows.Next() {
		var i ListExactDuplicatesRow
		if err := rows.Scan(&i.ContentHash, &i.DeviceSerial, &i.RelPath); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNearDuplicates = `-- name: ListNearDuplicates :many
SELECT dhash, device_serial, rel_path
FROM photo_hashes
WHERE dhash IS NOT NULL
ORDER BY dhash
`

type ListNearDuplicatesRow struct {
	Dhash        sql.NullString
	DeviceSerial string
	RelPath      string
}

func (q *Queries) ListNearDuplicates(ctx context.Context) ([]ListNearDuplicatesRow, error) {
	rows, err := q.db.QueryContext(ctx, listNearDuplicates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNearDuplicatesRow
	for rows.Next() {
		var i ListNearDuplicatesRow
		if err := rows.Scan(&i.Dhash, &i.DeviceSerial, &i.RelPath); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPhotoHash = `-- name: UpsertPhotoHash :exec
INSERT INTO photo_hashes (device_serial, rel_path, dhash, content_hash)
VALUES (?, ?, ?, ?)
ON CONFLICT (device_serial, rel_path)
DO UPDATE SET
    dhash        = excluded.dhash,
    content_hash = excluded.content_hash,
    computed_at  = datetime('now')
`

type UpsertPhotoHashParams struct {
	DeviceSerial string
	RelPath      string
	Dhash        sql.NullString
	ContentHash  sql.NullString
}

func (q *Queries) UpsertPhotoHash(ctx context.Context, arg UpsertPhotoHashParams) error {
	_, err := q.db.ExecContext(ctx, upsertPhotoHash,
		arg.DeviceSerial,
		arg.RelPath,
		arg.Dhash,
		arg.ContentHash,
	)
	return err
}
