// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: registered_devices.sql

package db

import (
	"context"
	"database/sql"
)

const approveDevice = `-- name: ApproveDevice :one
UPDATE registered_devices
SET
    approval_status = 'approved',
    approved_by     = ?,
    approved_at     = datetime('now'),
    updated_at      = datetime('now')
WHERE id = ?
RETURNING id, name, device_type, identity_type, ip_address, mac_address, tailscale_key, user_agent, approval_status, approved_by, approved_at, created_at, updated_at
`

type ApproveDeviceParams struct {
	ApprovedBy sql.NullString
	ID         int64
}

func (q *Queries) ApproveDevice(ctx context.Context, arg ApproveDeviceParams) (RegisteredDevice, error) {
	row := q.db.QueryRowContext(ctx, approveDevice, arg.ApprovedBy, arg.ID)
	var i RegisteredDevice
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DeviceType,
		&i.IdentityType,
		&i.IpAddress,
		&i.MacAddress,
		&i.TailscaleKey,
		&i.UserAgent,
		&i.ApprovalStatus,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countPendingDevices = `-- name: CountPendingDevices :one
SELECT COUNT(*) FROM registered_devices WHERE approval_status = 'pending'
`

func (q *Queries) CountPendingDevices(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPendingDevices)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteRegisteredDevice = `-- name: DeleteRegisteredDevice :exec
DELETE FROM registered_devices WHERE id = ?
`

func (q *Queries) DeleteRegisteredDevice(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteRegisteredDevice, id)
	return err
}

const getRegisteredDevice = `-- name: GetRegisteredDevice :one
SELECT id, name, device_type, identity_type, ip_address, mac_address, tailscale_key, user_agent, approval_status, approved_by, approved_at, created_at, updated_at FROM registered_devices WHERE id = ? LIMIT 1
`

func (q *Queries) GetRegisteredDevice(ctx context.Context, id int64) (RegisteredDevice, error) {
	row := q.db.QueryRowContext(ctx, getRegisteredDevice, id)
	var i RegisteredDevice
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DeviceType,
		&i.IdentityType,
		&i.IpAddress,
		&i.MacAddress,
		&i.TailscaleKey,
		&i.UserAgent,
		&i.ApprovalStatus,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRegisteredDeviceByIPUA = `-- name: GetRegisteredDeviceByIPUA :one
SELECT id, name, device_type, identity_type, ip_address, mac_address, tailscale_key, user_agent, approval_status, approved_by, approved_at, created_at, updated_at FROM registered_devices
WHERE ip_address = ? AND user_agent = ? AND tailscale_key IS NULL
LIMIT 1
`

type GetRegisteredDeviceByIPUAParams struct {
	IpAddress string
	UserAgent string
}

func (q *Queries) GetRegisteredDeviceByIPUA(ctx context.Context, arg GetRegisteredDeviceByIPUAParams) (RegisteredDevice, error) {
	row := q.db.QueryRowContext(ctx, getRegisteredDeviceByIPUA, arg.IpAddress, arg.UserAgent)
	var i RegisteredDevice
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DeviceType,
		&i.IdentityType,
		&i.IpAddress,
		&i.MacAddress,
		&i.TailscaleKey,
		&i.UserAgent,
		&i.ApprovalStatus,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRegisteredDeviceByTSKey = `-- name: GetRegisteredDeviceByTSKey :one
SELECT id, name, device_type, identity_type, ip_address, mac_address, tailscale_key, user_agent, approval_status, approved_by, approved_at, created_at, updated_at FROM registered_devices
WHERE tailscale_key = ?
LIMIT 1
`

func (q *Queries) GetRegisteredDeviceByTSKey(ctx context.Context, tailscaleKey sql.NullString) (RegisteredDevice, error) {
	row := q.db.QueryRowContext(ctx, getRegisteredDeviceByTSKey, tailscaleKey)
	var i RegisteredDevice
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DeviceType,
		&i.IdentityType,
		&i.IpAddress,
		&i.MacAddress,
		&i.TailscaleKey,
		&i.UserAgent,
		&i.ApprovalStatus,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRegisteredDevices = `-- name: ListRegisteredDevices :many
SELECT id, name, device_type, identity_type, ip_address, mac_address, tailscale_key, user_agent, approval_status, approved_by, approved_at, created_at, updated_at FROM registered_devices ORDER BY created_at DESC
`

func (q *Queries) ListRegisteredDevices(ctx context.Context) ([]RegisteredDevice, error) {
	rows, err := q.db.QueryContext(ctx, listRegisteredDevices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RegisteredDevice
	for rows.Next() {
		var i RegisteredDevice
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DeviceType,
			&i.IdentityType,
			&i.IpAddress,
			&i.MacAddress,
			&i.TailscaleKey,
			&i.UserAgent,
			&i.ApprovalStatus,
			&i.ApprovedBy,
			&i.ApprovedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRegisteredDevicesByStatus = `-- name: ListRegisteredDevicesByStatus :many
SELECT id, name, device_type, identity_type, ip_address, mac_address, tailscale_key, user_agent, approval_status, approved_by, approved_at, created_at, updated_at FROM registered_devices WHERE approval_status = ? ORDER BY created_at DESC
`

func (q *Queries) ListRegisteredDevicesByStatus(ctx context.Context, approvalStatus string) ([]RegisteredDevice, error) {
	rows, err := q.db.QueryContext(ctx, listRegisteredDevicesByStatus, approvalStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RegisteredDevice
	for rows.Next() {
		var i RegisteredDevice
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DeviceType,
			&i.IdentityType,
			&i.IpAddress,
			&i.MacAddress,
			&i.TailscaleKey,
			&i.UserAgent,
			&i.ApprovalStatus,
			&i.ApprovedBy,
			&i.ApprovedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const registerDevice = `-- name: RegisterDevice :one
INSERT INTO registered_devices (name, device_type, identity_type, ip_address, mac_address, tailscale_key, user_agent)
VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (ip_address, user_agent)
DO UPDATE SET
    name         = excluded.name,
    device_type  = excluded.device_type,
    user_agent   = excluded.user_agent,
    updated_at   = datetime('now')
RETURNING id, name, device_type, identity_type, ip_address, mac_address, tailscale_key, user_agent, approval_status, approved_by, approved_at, created_at, updated_at
`

type RegisterDeviceParams struct {
	Name         string
	DeviceType   string
	IdentityType string
	IpAddress    string
	MacAddress   sql.NullString
	TailscaleKey sql.NullString
	UserAgent    string
}

func (q *Queries) RegisterDevice(ctx context.Context, arg RegisterDeviceParams) (RegisteredDevice, error) {
	row := q.db.QueryRowContext(ctx, registerDevice,
		arg.Name,
		arg.DeviceType,
		arg.IdentityType,
		arg.IpAddress,
		arg.MacAddress,
		arg.TailscaleKey,
		arg.UserAgent,
	)
	var i RegisteredDevice
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DeviceType,
		&i.IdentityType,
		&i.IpAddress,
		&i.MacAddress,
		&i.TailscaleKey,
		&i.UserAgent,
		&i.ApprovalStatus,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const registerTailscaleDevice = `-- name: RegisterTailscaleDevice :one
INSERT INTO registered_devices (name, device_type, identity_type, ip_address, tailscale_key, user_agent)
VALUES (?, ?, 'tailscale', ?, ?, ?)
ON CONFLICT (tailscale_key)
DO UPDATE SET
    name        = excluded.name,
    device_type = excluded.device_type,
    ip_address  = excluded.ip_address,
    user_agent  = excluded.user_agent,
    updated_at  = datetime('now')
RETURNING id, name, device_type, identity_type, ip_address, mac_address, tailscale_key, user_agent, approval_status, approved_by, approved_at, created_at, updated_at
`

type RegisterTailscaleDeviceParams struct {
	Name         string
	DeviceType   string
	IpAddress    string
	TailscaleKey sql.NullString
	UserAgent    string
}

func (q *Queries) RegisterTailscaleDevice(ctx context.Context, arg RegisterTailscaleDeviceParams) (RegisteredDevice, error) {
	row := q.db.QueryRowContext(ctx, registerTailscaleDevice,
		arg.Name,
		arg.DeviceType,
		arg.IpAddress,
		arg.TailscaleKey,
		arg.UserAgent,
	)
	var i RegisteredDevice
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DeviceType,
		&i.IdentityType,
		&i.IpAddress,
		&i.MacAddress,
		&i.TailscaleKey,
		&i.UserAgent,
		&i.ApprovalStatus,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const revokeDevice = `-- name: RevokeDevice :one
UPDATE registered_devices
SET
    approval_status = 'revoked',
    approved_by     = ?,
    approved_at     = datetime('now'),
    updated_at      = datetime('now')
WHERE id = ?
RETURNING id, name, device_type, identity_type, ip_address, mac_address, tailscale_key, user_agent, approval_status, approved_by, approved_at, created_at, updated_at
`

type RevokeDeviceParams struct {
	ApprovedBy sql.NullString
	ID         int64
}

func (q *Queries) RevokeDevice(ctx context.Context, arg RevokeDeviceParams) (RegisteredDevice, error) {
	row := q.db.QueryRowContext(ctx, revokeDevice, arg.ApprovedBy, arg.ID)
	var i RegisteredDevice
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DeviceType,
		&i.IdentityType,
		&i.IpAddress,
		&i.MacAddress,
		&i.TailscaleKey,
		&i.UserAgent,
		&i.ApprovalStatus,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
