// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: share_links.sql

package db

import (
	"context"
	"database/sql"
)

const createShareLink = `-- name: CreateShareLink :one
INSERT INTO share_links (token, device_serial, rel_path, password_hash, max_uses, expires_at, created_by)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id
`

type CreateShareLinkParams struct {
	Token        string
	DeviceSerial string
	RelPath      string
	PasswordHash string
	MaxUses      int64
	ExpiresAt    sql.NullTime
	CreatedBy    string
}

func (q *Queries) CreateShareLink(ctx context.Context, arg CreateShareLinkParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createShareLink,
		arg.Token,
		arg.DeviceSerial,
		arg.RelPath,
		arg.PasswordHash,
		arg.MaxUses,
		arg.ExpiresAt,
		arg.CreatedBy,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteExpiredShareLinks = `-- name: DeleteExpiredShareLinks :exec
DELETE FROM share_links
WHERE expires_at IS NOT NULL AND expires_at < datetime('now')
`

func (q *Queries) DeleteExpiredShareLinks(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredShareLinks)
	return err
}

const deleteShareLink = `-- name: DeleteShareLink :exec
DELETE FROM share_links WHERE id = ?
`

func (q *Queries) DeleteShareLink(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteShareLink, id)
	return err
}

const getShareLinkByToken = `-- name: GetShareLinkByToken :one
SELECT id, token, device_serial, rel_path, password_hash, max_uses, use_count, expires_at, created_at, created_by FROM share_links WHERE token = ? LIMIT 1
`

func (q *Queries) GetShareLinkByToken(ctx context.Context, token string) (ShareLink, error) {
	row := q.db.QueryRowContext(ctx, getShareLinkByToken, token)
	var i ShareLink
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.DeviceSerial,
		&i.RelPath,
		&i.PasswordHash,
		&i.MaxUses,
		&i.UseCount,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const incrementShareLinkUseCount = `-- name: IncrementShareLinkUseCount :exec
UPDATE share_links SET use_count = use_count + 1 WHERE token = ?
`

func (q *Queries) IncrementShareLinkUseCount(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, incrementShareLinkUseCount, token)
	return err
}

const listShareLinks = `-- name: ListShareLinks :many
SELECT id, token, device_serial, rel_path, password_hash, max_uses, use_count, expires_at, created_at, created_by FROM share_links ORDER BY created_at DESC LIMIT 100
`

func (q *Queries) ListShareLinks(ctx context.Context) ([]ShareLink, error) {
	rows, err := q.db.QueryContext(ctx, listShareLinks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShareLink
	for rows.Next() {
		var i ShareLink
		if err := rows.Scan(
			&i.ID,
			&i.Token,
			&i.DeviceSerial,
			&i.RelPath,
			&i.PasswordHash,
			&i.MaxUses,
			&i.UseCount,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
