// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_roles.sql

package db

import (
	"context"
	"time"
)

const countAdmins = `-- name: CountAdmins :one
SELECT COUNT(*) FROM users WHERE role IN ('owner', 'admin')
`

// Counts users with owner or admin role. Used to prevent demoting the last admin.
func (q *Queries) CountAdmins(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAdmins)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getUserRole = `-- name: GetUserRole :one
SELECT role FROM users WHERE id = ? LIMIT 1
`

func (q *Queries) GetUserRole(ctx context.Context, id int64) (string, error) {
	row := q.db.QueryRowContext(ctx, getUserRole, id)
	var role string
	err := row.Scan(&role)
	return role, err
}

const isAdmin = `-- name: IsAdmin :one
SELECT CASE WHEN role IN ('owner', 'admin') THEN 1 ELSE 0 END FROM users WHERE id = ? LIMIT 1
`

// Returns 1 if the user has owner or admin role, 0 otherwise.
func (q *Queries) IsAdmin(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, isAdmin, id)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const listUserRoles = `-- name: ListUserRoles :many
SELECT id, username, role, created_at FROM users ORDER BY id ASC
`

type ListUserRolesRow struct {
	ID        int64
	Username  string
	Role      string
	CreatedAt time.Time
}

func (q *Queries) ListUserRoles(ctx context.Context) ([]ListUserRolesRow, error) {
	rows, err := q.db.QueryContext(ctx, listUserRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserRolesRow
	for rows.Next() {
		var i ListUserRolesRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Role,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserRole = `-- name: SetUserRole :exec
UPDATE users SET role = ? WHERE id = ?
`

type SetUserRoleParams struct {
	Role string
	ID   int64
}

func (q *Queries) SetUserRole(ctx context.Context, arg SetUserRoleParams) error {
	_, err := q.db.ExecContext(ctx, setUserRole, arg.Role, arg.ID)
	return err
}
